version: "3.8"
services:
  app:
    container_name: app
    build: "."
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - "postgres"
  postgres:
    container_name: postgres
    image:
      postgres:15.2-alpine
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - .env

volumes:
  postgres_data: